version: '3'
services:
  admin-page:
    build:
      context: ./admin_page
      dockerfile: Dockerfile
    volumes:
      - ./admin_page/data:/app/data
    environment:
      - STREAMLIT_SERVER_PORT=5000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_BASE_URL=/admin
    networks:
      - app-network

  frontend:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - backend
      - admin-page
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      chromadb:
        condition: service_healthy
    networks:
      - app-network

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  xai-service:
    build:
      context: ./xai_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./xai_service/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chroma_data:
